"""init

Revision ID: 3c0f71055392
Revises: 5360a59838c9
Create Date: 2021-05-28 15:23:26.754042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0f71055392'
down_revision = '5360a59838c9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user'))
    )
    op.create_index('admin_index', 'admin_user', ['login'], unique=True, mysql_length=255)
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('mail', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume'))
    )
    op.create_index('resume_index', 'resume', ['last_name'], unique=True, mysql_length=255)
    op.create_table('vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancy'))
    )
    op.create_index('vacancy_index', 'vacancy', ['title'], unique=True, mysql_length=255)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('vacancy_index', table_name='vacancy', mysql_length=255)
    op.drop_table('vacancy')
    op.drop_index('resume_index', table_name='resume', mysql_length=255)
    op.drop_table('resume')
    op.drop_index('admin_index', table_name='admin_user', mysql_length=255)
    op.drop_table('admin_user')
    # ### end Alembic commands ###
