"""init

Revision ID: ac04130e2f48
Revises: 3c0f71055392
Create Date: 2021-05-28 17:53:37.621729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac04130e2f48'
down_revision = '3c0f71055392'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('location', sa.Enum('location', name='locationenum'), nullable=True))
    op.add_column('vacancy', sa.Column('position', sa.Enum('position1', 'position2', name='positionenum'), nullable=True))
    op.add_column('vacancy', sa.Column('time_work', sa.Enum('time_work1', 'time_work2', name='timeworkenum'), nullable=True))
    op.add_column('vacancy', sa.Column('work_need', sa.Enum('work_need1', 'work_need2', name='workneedenum'), nullable=True))
    op.add_column('vacancy', sa.Column('benefits', sa.Enum('benefits', name='benefitsenum'), nullable=True))
    op.drop_column('vacancy', 'value')
    op.drop_column('vacancy', 'name')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('name', sa.TEXT(), nullable=True))
    op.add_column('vacancy', sa.Column('value', sa.INTEGER(), nullable=True))
    op.drop_column('vacancy', 'benefits')
    op.drop_column('vacancy', 'work_need')
    op.drop_column('vacancy', 'time_work')
    op.drop_column('vacancy', 'position')
    op.drop_column('vacancy', 'location')
    # ### end Alembic commands ###
